name: desafio_mi
description: Desafio Layout em Flutter para vaga do laboratório de segurança em computação da UFSC em parceria com o INMETRO.

publish_to: "none" # Não remova! Isso pode acidentalmente publicar o projeto em pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^2.1.0
  sentry_flutter: ^5.1.0 #debug de erros
  badges: ^2.0.1
  http: ^0.13.3
  json_annotation: ^4.0.1
  provider: ^5.0.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.4
  json_serializable: ^4.1.3

flutter:
  uses-material-design: true

  assets:
    - assets/
